[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "LEADRAT_API_KEY,LEADRAT_KEY_AMIT_THAKUR,LEADRAT_KEY_GAUTHAM_NANDU,LEADRAT_KEY_VIDHI_NANDA,LEADRAT_KEY_DIGVIJAY_CHARAN,LEADRAT_KEY_RAMESH_MALOTH,LEADRAT_KEY_AFTAB_KHAN,LEADRAT_KEY_FAHIM_KHAN,LEADRAT_KEY_MAHEBUB_RADHANPURI,LEADRAT_KEY_LALIT_SINGH,LEADRAT_KEY_BHARTI_MANCHANDA,INSTAGRAM_ACCESS_TOKEN,INSTAGRAM_USER_ID"
